# -*- coding: utf-8 -*-
"""
duvarkagidikaplama.com — site verisi.

Sayfa mimarisi bilinçli olarak DAR tutuldu (2026-08-28 kullanıcı kararı):
39 ilçe × 4 anahtar kelime + 39 ilçe × ~120 kullanım alanı = ~4.840 sayfalık
tam matris, Google'ın "ölçeklendirilmiş içeriği kötüye kullanma" politikasına
girer ve aynı niyetin varyasyonları birbirini yer (kannibalizasyon). Onun yerine:

  1 anasayfa + 39 ilçe sayfası (her biri 4 kelimeyi TEK sayfada kapsar)
  + 17 kullanım alanı sayfası (İstanbul geneli, gerçekten farklı içerik)
  + 6 rehber sayfası  =  63 sayfa

İlçe × kullanım alanı kombinasyonları 2-3 ay sonra Search Console verisiyle,
gerçekten arama alan kombinasyonlar için açılacak.
"""

SITE = {
    "ad": "duvarkagidikaplama.com",
    "marka": "Duvar Kağıdı Kaplama",
    "slogan": "Duvarlarınıza Yeni Bir Hikâye",
    "alan": "https://duvarkagidikaplama.com",
    "tel": "0546 456 54 65",
    "tel_link": "+905464565465",
    "wa": "905464565465",
    "sehir": "İstanbul",
    "aciklama": "İstanbul genelinde duvar kağıdı kaplama, tavan duvar kağıdı ve "
                "dijital özel baskı poster uygulaması. Ücretsiz keşif, rulo bazında "
                "net fiyat, temiz işçilik.",
}

# ── Fiyat listesi (kullanıcının verdiği güncel liste) ────────────────────────
# ⚠️ Fiyatlar TEK yerden okunur: sayfaların içine elle yazılmaz. Zam geldiğinde
# burayı değiştirmek 63 sayfanın tamamını günceller.
FIYAT_GUNCELLEME = "Ağustos 2026"

FIYATLAR = [
    {
        "grup": "Duvar Kağıdı",
        "ikon": "rulo",
        "kalemler": [
            ("Duvar kağıdı satış fiyatı", "3.000 ₺'den başlar", "1 rulo · 15,5 m² · 106 cm en"),
            ("Duvar kağıdı işçiliği", "1.500 ₺ / rulo", "İşçilik rulo bazında hesaplanır"),
        ],
    },
    {
        "grup": "Tavan Duvar Kağıdı",
        "ikon": "tavan",
        "kalemler": [
            ("Tavan duvar kağıdı satış fiyatı", "4.500 ₺ / rulo", "Tavana özel malzeme ve tutuş"),
            ("Tavan duvar kağıdı işçiliği", "2.500 ₺ / rulo", "Baş üstü çalışma, iki kişilik uygulama"),
        ],
    },
    {
        "grup": "Dijital Özel Baskı Poster",
        "ikon": "baski",
        "kalemler": [
            ("Özel baskı poster satış fiyatı", "600 ₺ / m²", "Kendi görselinizle, ölçüye özel baskı"),
            ("Özel baskı poster işçiliği", "200 ₺ / m²", "m² üzerinden uygulama"),
        ],
    },
]

FIYAT_NOTU = ("Fiyatlar bilgilendirme amaçlıdır. Net fiyat, uygulanacak alanın ölçüsüne ve "
              "seçilecek ürüne göre belirlenir. Ücretsiz keşifte duvarı ölçer, kaç rulo "
              "gideceğini ve toplam tutarı yazılı olarak veririm.")

# 1 rulo = 15,5 m² → hesap makinesi ve örnek hesaplar bu iki sayıdan üretilir.
RULO_M2 = 15.5
RULO_EN_CM = 106
RULO_SATIS = 3000
RULO_ISCILIK = 1500
TAVAN_SATIS = 4500
TAVAN_ISCILIK = 2500
POSTER_SATIS = 600
POSTER_ISCILIK = 200

# ── İstanbul'un 39 ilçesi ────────────────────────────────────────────────────
# doku : ilçenin yapı stoğu — sayfanın özgün paragrafı buradan doğar.
# vurgu: o ilçede işin pratikte değişen tarafı (asansör, tavan yüksekliği, nem…).
ILCELER = [
    dict(ad="Adalar", slug="adalar", yaka="Avrupa",
         mahalle=["Büyükada", "Heybeliada", "Burgazada", "Kınalıada"],
         doku="ahşap köşkler, yazlık evler ve düşük katlı taş binalar",
         vurgu="Adalar'da malzeme vapurla ve at arabası yerine el arabasıyla taşınıyor; bu yüzden ölçüyü bir kerede doğru alıp rulo sayısını şaşmadan hesaplamak şart",
         komsu=["kartal", "maltepe", "pendik"]),
    dict(ad="Arnavutköy", slug="arnavutkoy", yaka="Avrupa",
         mahalle=["Hadımköy", "Taşoluk", "Bolluca", "Haraççı", "Merkez"],
         doku="müstakil evler, yeni toplu konut siteleri ve depo-fabrika ofisleri",
         vurgu="Arnavutköy'de müstakil evlerin dış duvara bakan yüzeylerinde nem sık çıkıyor; kağıttan önce duvarın kuru olduğunu görmeden başlamıyorum",
         komsu=["basaksehir", "eyupsultan", "catalca", "buyukcekmece", "sultangazi"]),
    dict(ad="Ataşehir", slug="atasehir", yaka="Anadolu",
         mahalle=["Barbaros", "Küçükbakkalköy", "İçerenköy", "Ferhatpaşa", "Ataşehir Merkez"],
         doku="rezidans kuleleri, plaza katları ve 2000 sonrası siteler",
         vurgu="Ataşehir'de iş çoğunlukla rezidans ve ofis; site yönetiminden asansör ve saat izni almak, işin kendisi kadar planlama istiyor",
         komsu=["kadikoy", "umraniye", "maltepe", "sancaktepe"]),
    dict(ad="Avcılar", slug="avcilar", yaka="Avrupa",
         mahalle=["Cihangir", "Ambarlı", "Denizköşkler", "Merkez", "Üniversite"],
         doku="1990-2010 arası apartmanlar, öğrenci daireleri ve sahil siteleri",
         vurgu="Avcılar'da eski apartmanlarda duvar çoğu zaman kireç badanalı çıkıyor; astar atlanırsa kağıt bir yıl içinde kenardan kalkıyor",
         komsu=["esenyurt", "kucukcekmece", "beylikduzu", "basaksehir"]),
    dict(ad="Bağcılar", slug="bagcilar", yaka="Avrupa",
         mahalle=["Güneşli", "Kirazlı", "Yıldıztepe", "Demirkapı", "Merkez"],
         doku="yoğun apartman dokusu, iş hanları ve imalathane ofisleri",
         vurgu="Bağcılar'da hem ev hem iş yeri işi geliyor; iş yerlerinde çalışmayı akşam saatine alıp sabaha teslim ediyorum, dükkan bir gün bile kapanmıyor",
         komsu=["bahcelievler", "gungoren", "esenler", "basaksehir", "kucukcekmece"]),
    dict(ad="Bahçelievler", slug="bahcelievler", yaka="Avrupa",
         mahalle=["Şirinevler", "Yenibosna", "Soğanlı", "Kocasinan", "Siyavuşpaşa"],
         doku="orta yaşlı apartmanlar, AVM çevresi iş yerleri ve ofis katları",
         vurgu="Bahçelievler'de salon duvarı en çok istenen iş; tek duvar kaplaması genelde 2 rulo ile bitiyor",
         komsu=["bagcilar", "bakirkoy", "gungoren", "kucukcekmece"]),
    dict(ad="Bakırköy", slug="bakirkoy", yaka="Avrupa",
         mahalle=["Ataköy", "Yeşilköy", "Florya", "Yeşilyurt", "Şenlikköy"],
         doku="Ataköy siteleri, Florya-Yeşilköy villaları ve sahil rezidansları",
         vurgu="Bakırköy'de tavan yükseklikleri sık sık 3 metreyi geçiyor; standart rulo boyu yetmediği için ölçü almadan rulo sayısı söylemiyorum",
         komsu=["bahcelievler", "zeytinburnu", "kucukcekmece"]),
    dict(ad="Başakşehir", slug="basaksehir", yaka="Avrupa",
         mahalle=["Kayaşehir", "Başak", "Ziya Gökalp", "Bahçeşehir", "Güvercintepe"],
         doku="yeni toplu konut blokları, rezidanslar ve Bahçeşehir villaları",
         vurgu="Başakşehir'de daireler yeni olduğu için duvar zaten düzgün; işin tamamı çoğu zaman tek günde bitiyor",
         komsu=["arnavutkoy", "esenyurt", "bagcilar", "sultangazi", "avcilar", "kucukcekmece"]),
    dict(ad="Bayrampaşa", slug="bayrampasa", yaka="Avrupa",
         mahalle=["Yenidoğan", "Muratpaşa", "Kartaltepe", "Terazidere", "Vatan"],
         doku="apartmanlar, iş hanları ve toptancı ofisleri",
         vurgu="Bayrampaşa'da iş hanı ofisleri çok; mesai bitiminde girip gece uygulayıp sabah çalışır hâlde teslim etmek burada alıştığım bir düzen",
         komsu=["esenler", "gaziosmanpasa", "eyupsultan", "zeytinburnu", "fatih"]),
    dict(ad="Beşiktaş", slug="besiktas", yaka="Avrupa",
         mahalle=["Levent", "Etiler", "Ortaköy", "Bebek", "Gayrettepe"],
         doku="eski karakterli apartmanlar, lüks daireler ve ofis katları",
         vurgu="Beşiktaş'ta bina girişleri dar, park sorunlu; malzemeyi tek seferde ve ölçülü getirmek işin yarısı",
         komsu=["sisli", "sariyer", "kagithane", "beyoglu"]),
    dict(ad="Beykoz", slug="beykoz", yaka="Anadolu",
         mahalle=["Kavacık", "Paşabahçe", "Anadoluhisarı", "Çubuklu", "Acarkent"],
         doku="villalar, müstakil evler, yalı daireleri ve Kavacık ofisleri",
         vurgu="Beykoz'da boğaza bakan evlerde nem yüksek; nefes alan malzeme seçmek burada tercih değil zorunluluk",
         komsu=["uskudar", "umraniye", "cekmekoy", "sariyer"]),
    dict(ad="Beylikdüzü", slug="beylikduzu", yaka="Avrupa",
         mahalle=["Barış", "Cumhuriyet", "Gürpınar", "Yakuplu", "Adnan Kahveci"],
         doku="yeni siteler, rezidanslar ve geniş salonlu 3+1 daireler",
         vurgu="Beylikdüzü'nde salonlar geniş ve duvarlar uzun; TV duvarı kaplaması burada en çok istenen iş",
         komsu=["esenyurt", "buyukcekmece", "avcilar"]),
    dict(ad="Beyoğlu", slug="beyoglu", yaka="Avrupa",
         mahalle=["Cihangir", "Galata", "Tarlabaşı", "Kasımpaşa", "Taksim"],
         doku="tarihi binalar, çatı katları, butik oteller ve kafe-restoranlar",
         vurgu="Beyoğlu'nda tarihi binalarda duvar hiçbir zaman düz değil; bu evlerde desen seçimi kadar duvar hazırlığı da işin ana kalemi",
         komsu=["sisli", "besiktas", "fatih", "kagithane"]),
    dict(ad="Büyükçekmece", slug="buyukcekmece", yaka="Avrupa",
         mahalle=["Mimarsinan", "Kumburgaz", "Atatürk", "Türkoba", "Güzelce"],
         doku="villalar, yazlık siteler ve göl çevresi yeni konutlar",
         vurgu="Büyükçekmece'de yazlık evler kışın kapalı kalıyor; kapalı evde rutubet biriktiği için uygulamadan önce mutlaka havalandırma istiyorum",
         komsu=["beylikduzu", "esenyurt", "catalca", "silivri"]),
    dict(ad="Çatalca", slug="catalca", yaka="Avrupa",
         mahalle=["Ferhatpaşa", "Kaleiçi", "Ortaköy", "Hallaçlı", "Merkez"],
         doku="müstakil evler, köy evleri ve çiftlik-bağ evleri",
         vurgu="Çatalca'ya bir günde gidip dönmek için ölçü ve malzemeyi tek seferde netleştiriyorum; yolu uzun diye ikinci sefer olmuyor",
         komsu=["arnavutkoy", "buyukcekmece", "silivri"]),
    dict(ad="Çekmeköy", slug="cekmekoy", yaka="Anadolu",
         mahalle=["Taşdelen", "Alemdağ", "Ömerli", "Mimar Sinan", "Merkez"],
         doku="villalar, bahçeli müstakil evler ve yeni siteler",
         vurgu="Çekmeköy'de merdiven boşluğu ve yüksek hol duvarları çok çıkıyor; bu işler iskele ve iki kişi istiyor",
         komsu=["umraniye", "sancaktepe", "beykoz", "sultanbeyli"]),
    dict(ad="Esenler", slug="esenler", yaka="Avrupa",
         mahalle=["Menderes", "Havaalanı", "Fevzi Çakmak", "Nine Hatun", "Oruçreis"],
         doku="apartmanlar, kentsel dönüşümle yenilenen bloklar ve iş yerleri",
         vurgu="Esenler'de yeni teslim dönüşüm dairelerinde alçı taze oluyor; alçı tam kurumadan kağıt yapıştırmak en sık gördüğüm hata",
         komsu=["bagcilar", "bayrampasa", "gungoren", "sultangazi", "gaziosmanpasa"]),
    dict(ad="Esenyurt", slug="esenyurt", yaka="Avrupa",
         mahalle=["Cumhuriyet", "Yenikent", "İnönü", "Örnek", "Talatpaşa", "Saadetdere"],
         doku="yeni siteler, rezidans blokları ve 2+1 - 3+1 daireler",
         vurgu="Esenyurt İstanbul'un en çok daire teslim edilen ilçesi; yeni taşınan evlerde tek duvar kaplaması hem hızlı hem en çok tercih edilen iş",
         komsu=["avcilar", "beylikduzu", "basaksehir", "buyukcekmece", "kucukcekmece"]),
    dict(ad="Eyüpsultan", slug="eyupsultan", yaka="Avrupa",
         mahalle=["Alibeyköy", "Göktürk", "Kemerburgaz", "Yeşilpınar", "Merkez"],
         doku="eski merkez apartmanları ile Göktürk-Kemerburgaz villa siteleri",
         vurgu="Eyüpsultan tek bir doku değil: Alibeyköy'de apartman, Göktürk'te villa işi yapıyorum; ölçü ve malzeme ikisinde bambaşka",
         komsu=["kagithane", "gaziosmanpasa", "sariyer", "arnavutkoy", "bayrampasa"]),
    dict(ad="Fatih", slug="fatih", yaka="Avrupa",
         mahalle=["Aksaray", "Fındıkzade", "Çapa", "Balat", "Sultanahmet"],
         doku="tarihi yapılar, otel-pansiyonlar, iş hanları ve eski apartmanlar",
         vurgu="Fatih'te otel ve pansiyon işi çok; oda boşken girip aynı gün teslim etmek burada standart çalışma şeklim",
         komsu=["zeytinburnu", "bayrampasa", "eyupsultan", "beyoglu"]),
    dict(ad="Gaziosmanpaşa", slug="gaziosmanpasa", yaka="Avrupa",
         mahalle=["Karadeniz", "Karayolları", "Sarıgöl", "Yenimahalle", "Merkez"],
         doku="apartmanlar ve kentsel dönüşümle yenilenen bloklar",
         vurgu="Gaziosmanpaşa'da bütçe hassas; hangi rulonun gerçekten gerekli olduğunu, nerede tek duvarın yeteceğini açık söylüyorum",
         komsu=["eyupsultan", "sultangazi", "bayrampasa", "esenler"]),
    dict(ad="Güngören", slug="gungoren", yaka="Avrupa",
         mahalle=["Merter", "Tozkoparan", "Haznedar", "Güven", "Merkez"],
         doku="apartmanlar, Merter tekstil iş hanları ve showroom katları",
         vurgu="Merter'de showroom ve ofis işi ağırlıkta; müşteri karşılayan duvarın kusursuz olması gerektiği için ek yerlerini göz hizasından kaçırıyorum",
         komsu=["bagcilar", "bahcelievler", "esenler", "zeytinburnu"]),
    dict(ad="Kadıköy", slug="kadikoy", yaka="Anadolu",
         mahalle=["Moda", "Caferağa", "Fenerbahçe", "Kozyatağı", "Göztepe", "Bostancı"],
         doku="karakterli eski apartmanlar, yenilenen daireler, kafe ve ofisler",
         vurgu="Kadıköy'de 40-50 yıllık binalarda duvarlar dalgalı; burada kaplamadan önce duvar düzeltmeye ayırdığım süre, kağıdı yapıştırma süresinden uzun oluyor",
         komsu=["atasehir", "maltepe", "uskudar"]),
    dict(ad="Kağıthane", slug="kagithane", yaka="Avrupa",
         mahalle=["Çağlayan", "Gültepe", "Seyrantepe", "Merkez", "Hamidiye"],
         doku="plaza ve ofis katları ile kentsel dönüşüm konutları",
         vurgu="Kağıthane'de ofis işi çok; açık ofiste tek bir vurgu duvarı bile mekânın havasını değiştiriyor, üstelik boya kadar hızlı bitiyor",
         komsu=["sisli", "besiktas", "eyupsultan", "beyoglu", "sariyer"]),
    dict(ad="Kartal", slug="kartal", yaka="Anadolu",
         mahalle=["Soğanlık", "Yakacık", "Cevizli", "Orhantepe", "Kordonboyu"],
         doku="yeni rezidanslar, sahil siteleri ve eski apartmanlar",
         vurgu="Kartal'da sahile yakın dairelerde tuz ve nem etkisi var; dış duvara bakan yüzeyde malzemeyi ona göre seçiyorum",
         komsu=["maltepe", "pendik", "sancaktepe", "sultanbeyli"]),
    dict(ad="Küçükçekmece", slug="kucukcekmece", yaka="Avrupa",
         mahalle=["Halkalı", "Sefaköy", "Cennet", "Atakent", "İkitelli"],
         doku="toplu konut siteleri, apartmanlar ve İkitelli iş yerleri",
         vurgu="Küçükçekmece'de aynı sitede birbirinin aynı daireler var; bir dairede ölçü aldıktan sonra komşu blokta iş çok daha hızlı ilerliyor",
         komsu=["bagcilar", "bahcelievler", "avcilar", "basaksehir", "bakirkoy"]),
    dict(ad="Maltepe", slug="maltepe", yaka="Anadolu",
         mahalle=["Bağlarbaşı", "Cevizli", "Küçükyalı", "Altayçeşme", "Başıbüyük"],
         doku="sahil rezidansları, orta yaşlı apartmanlar ve yeni siteler",
         vurgu="Maltepe'de sahil tarafındaki dairelerde ışık çok; açık renk kağıt burada solmaya daha dayanıklı ürün seçmeyi gerektiriyor",
         komsu=["kadikoy", "kartal", "atasehir", "sancaktepe"]),
    dict(ad="Pendik", slug="pendik", yaka="Anadolu",
         mahalle=["Kaynarca", "Velibaba", "Çamçeşme", "Kurtköy", "Güzelyalı"],
         doku="yeni siteler, müstakil evler ve Kurtköy çevresi konutları",
         vurgu="Pendik geniş bir ilçe; Kurtköy ile sahil arası yarım saat çekiyor, o yüzden keşif ve uygulamayı aynı bölgede aynı güne denk getiriyorum",
         komsu=["kartal", "tuzla", "sultanbeyli", "sancaktepe"]),
    dict(ad="Sancaktepe", slug="sancaktepe", yaka="Anadolu",
         mahalle=["Sarıgazi", "Abdurrahmangazi", "Yenidoğan", "Emek", "Merve"],
         doku="yeni siteler, kentsel dönüşüm blokları ve müstakil evler",
         vurgu="Sancaktepe'de yeni teslim dairelerde duvar hazır; sabah başlayıp akşam biten tek gün işi burada çok sık",
         komsu=["umraniye", "cekmekoy", "sultanbeyli", "kartal", "atasehir"]),
    dict(ad="Sarıyer", slug="sariyer", yaka="Avrupa",
         mahalle=["Maslak", "Tarabya", "Yeniköy", "İstinye", "Bahçeköy"],
         doku="yalı daireleri, villalar, Maslak ofis kuleleri ve orman içi siteler",
         vurgu="Sarıyer'de hem yalı dairesi hem Maslak ofisi yapıyorum; ikisinde de ortak nokta, işin çalışma saatinin binaya göre planlanması",
         komsu=["besiktas", "sisli", "kagithane", "eyupsultan", "beykoz"]),
    dict(ad="Silivri", slug="silivri", yaka="Avrupa",
         mahalle=["Alibey", "Selimpaşa", "Değirmenköy", "Gümüşyaka", "Merkez"],
         doku="yazlık siteler, müstakil evler ve sahil konutları",
         vurgu="Silivri'de yazlıklar sezon başında topluca yenileniyor; nisan-mayıs döneminde randevuyu erken almak gerekiyor",
         komsu=["buyukcekmece", "catalca"]),
    dict(ad="Sultanbeyli", slug="sultanbeyli", yaka="Anadolu",
         mahalle=["Abdurrahmangazi", "Mehmet Akif", "Battalgazi", "Fatih", "Hasanpaşa"],
         doku="apartmanlar ve yeni yapılan bloklar",
         vurgu="Sultanbeyli'de çocuk odası işi çok geliyor; silinebilir yüzeyli ürün burada gerçekten fark yaratıyor",
         komsu=["sancaktepe", "pendik", "kartal", "cekmekoy"]),
    dict(ad="Sultangazi", slug="sultangazi", yaka="Avrupa",
         mahalle=["Cebeci", "Habibler", "50. Yıl", "Uğur Mumcu", "Esentepe"],
         doku="apartmanlar ve kentsel dönüşümle yenilenen konutlar",
         vurgu="Sultangazi'de bütçeye göre çözüm istiyorlar; tek duvar kaplaması ile odanın tamamını kaplamanın farkını rakamla gösteriyorum",
         komsu=["gaziosmanpasa", "eyupsultan", "esenler", "basaksehir", "arnavutkoy"]),
    dict(ad="Şile", slug="sile", yaka="Anadolu",
         mahalle=["Merkez", "Ağva", "Çayırbaşı", "Doğancılı", "Kumbaba"],
         doku="müstakil evler, yazlıklar ve bahçeli taş evler",
         vurgu="Şile'de deniz havası ve kışın kapalı kalan evler nem demek; burada ürün seçimi desenden önce geliyor",
         komsu=["cekmekoy", "beykoz", "pendik"]),
    dict(ad="Şişli", slug="sisli", yaka="Avrupa",
         mahalle=["Nişantaşı", "Mecidiyeköy", "Fulya", "Bomonti", "Esentepe"],
         doku="yüksek tavanlı eski apartmanlar, ofis katları ve rezidanslar",
         vurgu="Nişantaşı tarafında tavanlar 3,5 metreye çıkabiliyor; bu evlerde rulo hesabı standart tablodan değil, yerinde ölçüden çıkar",
         komsu=["besiktas", "kagithane", "beyoglu", "sariyer"]),
    dict(ad="Tuzla", slug="tuzla", yaka="Anadolu",
         mahalle=["Aydınlı", "İçmeler", "Postane", "Şifa", "Orhanlı"],
         doku="müstakil evler, yeni siteler ve organize sanayi ofisleri",
         vurgu="Tuzla'da fabrika ve sanayi ofisi işi çok; buralarda yoğun kullanıma dayanıklı, silinebilir ürün öneriyorum",
         komsu=["pendik"]),
    dict(ad="Ümraniye", slug="umraniye", yaka="Anadolu",
         mahalle=["Atakent", "Çakmak", "Tepeüstü", "Dudullu", "Finanskent"],
         doku="yeni rezidanslar, siteler ve Dudullu sanayi ofisleri",
         vurgu="Ümraniye'de hem yeni rezidans hem eski apartman var; keşifte ilk baktığım şey duvarın sıva mı alçı mı olduğu",
         komsu=["uskudar", "atasehir", "sancaktepe", "cekmekoy", "beykoz"]),
    dict(ad="Üsküdar", slug="uskudar", yaka="Anadolu",
         mahalle=["Acıbadem", "Kuzguncuk", "Çengelköy", "Bulgurlu", "Altunizade"],
         doku="eski apartmanlar, tarihi ahşap evler ve Altunizade ofisleri",
         vurgu="Üsküdar'ın sahil mahallelerinde eski binalarda rutubet sık; kağıdı yapıştırmadan önce duvarı nem ölçerle kontrol ediyorum",
         komsu=["kadikoy", "umraniye", "beykoz", "atasehir"]),
    dict(ad="Zeytinburnu", slug="zeytinburnu", yaka="Avrupa",
         mahalle=["Merkezefendi", "Telsiz", "Kazlıçeşme", "Beştelsiz", "Sümer"],
         doku="apartmanlar, tekstil iş yerleri ve yeni sahil rezidansları",
         vurgu="Zeytinburnu'nda iş yeri ve mağaza işi ağırlıkta; vitrine bakan duvarı gündüz kapatmadan, akşam çalışarak yapıyorum",
         komsu=["bakirkoy", "bahcelievler", "fatih", "gungoren", "bayrampasa"]),
]

# İlçe sayfasının kapsadığı 4 anahtar kelime — ayrı sayfa AÇILMAZ, aynı sayfada
# ayrı H2 bölümleri olarak geçer (kannibalizasyonu önlemek için bilinçli karar).
ILCE_KELIMELER = [
    ("{ad} duvar kağıdı kaplama", "kaplama"),
    ("{ad} duvar kağıdı satan yerler", "satan-yerler"),
    ("{ad} duvar kaplama", "duvar-kaplama"),
    ("{ad} duvar kağıdı ustası", "usta"),
]

# ── Kullanım alanı sayfaları (İstanbul geneli, 17 sayfa) ─────────────────────
# Bunlar ilçeye göre çoğaltılmaz. Sebebi: "otel duvar kağıdı" ile "kuaför duvar
# kağıdı" GERÇEKTEN farklı içerik ister (yanmazlık, yoğun kullanım, nem, ışık),
# ama "Esenyurt otel duvar kağıdı" ile "Avcılar otel duvar kağıdı" arasında
# yazılacak farklı hiçbir şey yok. İlçe sayfaları bu sayfalara link verir.
ALANLAR = [
    dict(slug="ev-duvar-kagidi", ad="Ev Duvar Kağıdı",
         h1="Ev Duvar Kağıdı Kaplama",
         ozet="Salondan antreye, evin her odası için duvar kağıdı seçimi, ölçü ve fiyat.",
         kapsam=["ev duvar kağıdı", "oturma odası duvar kağıdı", "antre duvar kağıdı",
                 "merdiven duvar kağıdı", "apartman duvar kağıdı"],
         aci="Evin tamamını kaplamak çoğu zaman gerekmiyor. Hangi odada tek duvarın yettiğini, "
             "hangisinde tüm duvarların kaplanması gerektiğini rakamla anlatıyorum."),
    dict(slug="salon-duvar-kagidi", ad="Salon Duvar Kağıdı",
         h1="Salon Duvar Kağıdı Kaplama",
         ozet="TV duvarı ve salon kaplaması: kaç rulo gider, hangi desen küçük salonu büyütür.",
         kapsam=["salon duvar kağıdı", "oturma odası duvar kağıdı", "tv duvarı duvar kağıdı"],
         aci="Salonda en sık yapılan iş TV ünitesinin arkasındaki tek duvar. 4 metrelik bir duvar "
             "genelde 2 rulo ile bitiyor; yani malzeme + işçilik toplamı net hesaplanabiliyor."),
    dict(slug="yatak-odasi-duvar-kagidi", ad="Yatak Odası Duvar Kağıdı",
         h1="Yatak Odası Duvar Kağıdı Kaplama",
         ozet="Yatak başı duvarı, dolap arkası ve tüm oda kaplaması için seçim ve fiyat.",
         kapsam=["yatak odası duvar kağıdı", "yatak başı duvar kağıdı"],
         aci="Yatak odasında kaplama neredeyse her zaman yatak başı duvarı. Dolabın kapattığı "
             "duvarı kaplatmak boşa para; keşifte bunu açıkça söylüyorum."),
    dict(slug="cocuk-odasi-duvar-kagidi", ad="Çocuk Odası Duvar Kağıdı",
         h1="Çocuk ve Bebek Odası Duvar Kağıdı",
         ozet="Silinebilir yüzey, kokusuz malzeme ve büyüyen çocuğa göre desen seçimi.",
         kapsam=["çocuk odası duvar kağıdı", "bebek odası duvar kağıdı",
                 "çocuk odası dekorasyon duvar kağıdı"],
         aci="Çocuk odasında iki şey önemli: silinebilir yüzey ve kokusuz malzeme. Desen ise "
             "çocuk 3 yaşındayken sevdiğiyle 8 yaşındayken sevdiği aynı olmuyor — bunu düşünerek seçin."),
    dict(slug="villa-rezidans-duvar-kagidi", ad="Villa ve Rezidans Duvar Kağıdı",
         h1="Villa ve Rezidans Duvar Kağıdı Kaplama",
         ozet="Yüksek tavan, merdiven boşluğu ve geniş hollerde duvar kağıdı uygulaması.",
         kapsam=["villa duvar kağıdı", "rezidans duvar kağıdı", "merdiven duvar kağıdı",
                 "apartman duvar kağıdı"],
         aci="Villa ve rezidansta işi zorlaştıran şey desen değil yükseklik. Merdiven boşluğu ve "
             "çift kat holler iskele ve iki kişilik ekip istiyor; fiyat da buna göre değişiyor."),
    dict(slug="ofis-duvar-kagidi", ad="Ofis Duvar Kağıdı",
         h1="Ofis Duvar Kağıdı Kaplama",
         ozet="Resepsiyon, toplantı odası ve açık ofis için duvar kağıdı uygulaması.",
         kapsam=["ofis duvar kağıdı", "plaza duvar kağıdı", "şirket ofisi duvar kağıdı",
                 "resepsiyon duvar kağıdı", "toplantı odası duvar kağıdı", "firma duvar kağıdı",
                 "ofise duvar kağıdı yaptırma", "ofis duvar kağıdı kaplama"],
         aci="Ofiste en çok işi resepsiyon arkası ve toplantı odası görüyor. Bu iki duvar "
             "firmanın vitrini; ek yerlerini göz hizasından kaçırmak burada teknik değil ticari mesele."),
    dict(slug="magaza-duvar-kagidi", ad="Mağaza ve Dükkan Duvar Kağıdı",
         h1="Mağaza, Dükkan ve Showroom Duvar Kağıdı",
         ozet="Vitrinli mağaza, dükkan ve showroom için gece çalışmalı duvar kağıdı uygulaması.",
         kapsam=["mağaza duvar kağıdı", "dükkan duvar kağıdı", "showroom duvar kağıdı",
                 "iş yeri duvar kağıdı", "mağazaya duvar kağıdı yaptırma",
                 "dükkan duvar kağıdı kaplama", "iş yeri duvar kağıdı kaplama",
                 "mağaza duvar kağıdı kaplama", "mobilya mağazası duvar kağıdı",
                 "dekorasyon mağazası duvar kağıdı", "perde mağazası duvar kağıdı"],
         aci="Mağazada asıl mesele dükkanı kapatmamak. Kepenk indikten sonra girip sabaha "
             "teslim ettiğim işler, bir günlük ciro kaybını sıfırlıyor."),
    dict(slug="otel-duvar-kagidi", ad="Otel Duvar Kağıdı",
         h1="Otel, Butik Otel ve Pansiyon Duvar Kağıdı",
         ozet="Otel odası, lobi ve koridor için dayanıklı duvar kağıdı uygulaması.",
         kapsam=["otel duvar kağıdı", "otel odası duvar kağıdı", "otel lobi duvar kağıdı",
                 "otel koridor duvar kağıdı", "butik otel duvar kağıdı", "pansiyon duvar kağıdı",
                 "apart otel duvar kağıdı", "otele duvar kağıdı yaptırma", "otel duvar kağıdı kaplama"],
         aci="Otelde koridor duvarı valizle çarpılır, oda duvarı her hafta silinir. Ev için "
             "gayet iyi olan bir ürün otelde altı ayda biter; burada ürün seçimi işin kendisinden önemli."),
    dict(slug="restoran-kafe-duvar-kagidi", ad="Restoran ve Kafe Duvar Kağıdı",
         h1="Restoran, Kafe ve Lokanta Duvar Kağıdı",
         ozet="Yeme-içme mekânlarında yağ, buhar ve yoğun kullanıma dayanıklı kaplama.",
         kapsam=["restoran duvar kağıdı", "kafe duvar kağıdı", "cafe duvar kağıdı",
                 "bar duvar kağıdı", "lokanta duvar kağıdı", "pastane duvar kağıdı",
                 "fırın duvar kağıdı", "kahve dükkanı duvar kağıdı", "nargile kafe duvar kağıdı",
                 "restorana duvar kağıdı yaptırma", "kafeye duvar kağıdı yaptırma",
                 "restoran duvar kağıdı kaplama"],
         aci="Mutfağa yakın duvarda yağ ve buhar var. Orada normal duvar kağıdı bir sezon "
             "dayanmıyor; silinebilir yüzeyli ürün ya da cam/panel ayrımını keşifte konuşuyoruz."),
    dict(slug="kuafor-guzellik-salonu-duvar-kagidi", ad="Kuaför ve Güzellik Salonu Duvar Kağıdı",
         h1="Kuaför, Berber ve Güzellik Salonu Duvar Kağıdı",
         ozet="Salon, spa ve estetik merkezleri için nem ve kimyasala dayanıklı kaplama.",
         kapsam=["kuaför duvar kağıdı", "berber duvar kağıdı", "güzellik salonu duvar kağıdı",
                 "estetik merkezi duvar kağıdı", "spa duvar kağıdı", "masaj salonu duvar kağıdı",
                 "tırnak salonu duvar kağıdı", "bayan kuaförü duvar kağıdı",
                 "erkek kuaförü duvar kağıdı", "kuaföre duvar kağıdı yaptırma",
                 "salona duvar kağıdı yaptırma"],
         aci="Kuaförde yıkama bölümü sürekli nemli, boya bölümünde kimyasal var. Ayna arkası "
             "duvarı ile yıkama duvarına aynı ürünü koymak, altı ay sonra iki kere iş demek."),
    dict(slug="klinik-duvar-kagidi", ad="Klinik ve Muayenehane Duvar Kağıdı",
         h1="Klinik, Diş Kliniği ve Muayenehane Duvar Kağıdı",
         ozet="Sağlık mekânlarında hijyen, silinebilirlik ve sakin renk seçimi.",
         kapsam=["klinik duvar kağıdı", "diş kliniği duvar kağıdı",
                 "doktor muayenehanesi duvar kağıdı", "özel hastane duvar kağıdı",
                 "poliklinik duvar kağıdı", "psikolog ofisi duvar kağıdı",
                 "veteriner kliniği duvar kağıdı", "eczane duvar kağıdı",
                 "laboratuvar duvar kağıdı", "kliniğe duvar kağıdı yaptırma"],
         aci="Klinikte duvar her gün siliniyor. Bekleme alanında hastayı sakinleştiren renk, "
             "muayene odasında ise tamamen silinebilir yüzey gerekiyor — ikisi aynı ürün değil."),
    dict(slug="okul-kres-duvar-kagidi", ad="Okul ve Kreş Duvar Kağıdı",
         h1="Okul, Anaokulu ve Kreş Duvar Kağıdı",
         ozet="Kreş, anaokulu ve dershanelerde kokusuz, silinebilir, güvenli kaplama.",
         kapsam=["okul duvar kağıdı", "özel okul duvar kağıdı", "anaokulu duvar kağıdı",
                 "kreş duvar kağıdı", "etüt merkezi duvar kağıdı", "dershane duvar kağıdı",
                 "kurs merkezi duvar kağıdı", "çocuk kreşi duvar kağıdı",
                 "çocuk oyun alanı duvar kağıdı"],
         aci="Kreşte duvarın 1 metreden aşağısı sürekli elleniyor. O bölgeye silinebilir ürün, "
             "üstüne istediğiniz deseni koymak hem daha ucuz hem daha uzun ömürlü."),
    dict(slug="spor-salonu-duvar-kagidi", ad="Spor Salonu Duvar Kağıdı",
         h1="Spor Salonu ve Fitness Duvar Kağıdı",
         ozet="Fitness, pilates ve dans stüdyolarında nem ve yoğun kullanıma dayanıklı kaplama.",
         kapsam=["spor salonu duvar kağıdı", "fitness salonu duvar kağıdı",
                 "dans stüdyosu duvar kağıdı"],
         aci="Spor salonunda terleme yüzünden nem yüksek, duvara sürekli temas var. Burada "
             "duvar kağıdını ayna ve ekipman olmayan yüzeylere planlamak gerekiyor."),
    dict(slug="dugun-salonu-duvar-kagidi", ad="Düğün Salonu Duvar Kağıdı",
         h1="Düğün Salonu ve Organizasyon Mekânı Duvar Kağıdı",
         ozet="Fotoğrafa giren duvarlar: düğün salonu, organizasyon ve stüdyo kaplaması.",
         kapsam=["düğün salonu duvar kağıdı", "organizasyon salonu duvar kağıdı",
                 "fotoğraf stüdyosu duvar kağıdı"],
         aci="Düğün salonunda duvar sadece dekor değil, fotoğrafın fonu. Parlak yüzey flaş "
             "patlatır; burada mat ürün seçmek fotoğrafçının işini kolaylaştırır."),
    dict(slug="buro-duvar-kagidi", ad="Büro ve Ofis Duvar Kağıdı",
         h1="Emlak, Hukuk ve Mimarlık Bürosu Duvar Kağıdı",
         ozet="Müşteri kabul eden küçük bürolarda güven veren duvar düzenlemesi.",
         kapsam=["emlak ofisi duvar kağıdı", "hukuk bürosu duvar kağıdı",
                 "mimarlık ofisi duvar kağıdı", "tasarım ofisi duvar kağıdı",
                 "oto galeri duvar kağıdı", "otomotiv showroom duvar kağıdı"],
         aci="Küçük büroda müşteri karşınızda oturuyor ve arkanızdaki duvara bakıyor. O tek "
             "duvarın düzgün olması, bütün ofisi toparlıyor."),
    dict(slug="tavan-duvar-kagidi", ad="Tavan Duvar Kağıdı",
         h1="Tavan Duvar Kağıdı Kaplama",
         ozet="Tavana duvar kağıdı: fiyatı, uygulaması ve nelere dikkat edilmeli.",
         kapsam=["tavan duvar kağıdı", "tavan kaplama duvar kağıdı"],
         aci="Tavan işi duvarın iki katı emek. Baş üstünde çalışılıyor, yapıştırıcı ağırlığı "
             "aşağı çekiyor ve tek kişiyle yapılmıyor. Fiyat farkının sebebi bu."),
    dict(slug="dijital-baski-duvar-kagidi", ad="Dijital Özel Baskı Duvar Kağıdı",
         h1="Dijital Özel Baskı Duvar Kağıdı ve Poster",
         ozet="Kendi görselinizi duvara basıyoruz: m² fiyatı, çözünürlük ve uygulama.",
         kapsam=["özel baskı duvar kağıdı", "dijital baskı duvar kağıdı", "poster duvar kağıdı",
                 "duvar posteri", "3d duvar kağıdı"],
         aci="Özel baskıda tek kritik nokta görselin çözünürlüğü. Telefondan gelen 1 MB'lik "
             "fotoğraf 3 metre duvara basılınca dağılıyor; baskıya girmeden bunu birlikte kontrol ediyoruz."),
]

# ── Rehber sayfaları (6) ─────────────────────────────────────────────────────
REHBERLER = [
    dict(slug="duvar-kagidi-kaplama-nedir", ad="Duvar Kağıdı Kaplama Nedir?",
         h1="Duvar Kağıdı Kaplama Nedir, Ne İşe Yarar?",
         ozet="Duvar kağıdı kaplamanın ne olduğu, boyaya göre farkı ve hangi durumda tercih edilmesi gerektiği."),
    dict(slug="duvar-kagidi-cesitleri", ad="Duvar Kağıdı Çeşitleri",
         h1="Duvar Kağıdı Çeşitleri ve Türleri",
         ozet="Vinil, non-woven, tekstil, cam elyaf ve özel baskı: hangisi nerede kullanılır."),
    dict(slug="duvar-kagidi-fiyatlari", ad="Duvar Kağıdı Fiyatları",
         h1="Duvar Kağıdı Fiyatları 2026",
         ozet="Rulo fiyatı, m² hesabı ve oda büyüklüğüne göre örnek toplam tutarlar."),
    dict(slug="duvar-kagidi-iscilik-fiyatlari", ad="Duvar Kağıdı İşçilik Fiyatları",
         h1="Duvar Kağıdı İşçilik Fiyatları 2026",
         ozet="İşçilik neden rulo bazında hesaplanır, tavan ve poster işçiliği neden farklıdır."),
    dict(slug="duvar-kagidi-omru", ad="Duvar Kağıdı Ömrü",
         h1="Duvar Kağıdı Kaç Yıl Dayanır?",
         ozet="Evde, ofiste ve otelde duvar kağıdının gerçek ömrü ve ömrü kısaltan hatalar."),
    dict(slug="duvar-kagidi-nasil-yapistirilir", ad="Duvar Kağıdı Nasıl Yapıştırılır?",
         h1="Duvar Kağıdı Nasıl Yapıştırılır? Uygulama Süreci",
         ozet="Keşiften teslime uygulama adımları, duvar hazırlığı ve sık yapılan hatalar."),
]
